version: 2
updates:
  # Monitoramento de dependências Python (pip)
  - package-ecosystem: "pip"
    directory: "/requirements.txt" 
    schedule:
      interval: "monthly" # daily, weekly ou monthly
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"

  # Monitoramento das ações do GitHub Actions (ci.yml)
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/ci.yml"
    schedule:
      interval: "weekly"
